spring.application.name=artwork-project
# ???? dev ?? (????????????)
spring.profiles.active=dev

# 1. ?????
server.port=8080

# 2. ?????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# 3. ?????? (50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 4. MyBatis Plus ??
mybatis-plus.configuration.map-underscore-to-camel-case=true
# ? ????????????
logging.level.com.design.artwork.mapper=debug


